server.port: ${port:8080}
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/new_db
    username: root
    password: best2580
  jpa:
    properties.hibernate.format_sql: true
  redis:
    host: localhost
    port: 6379
    password: best2580
  output.ansi.enabled: always
  main.allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true

logging.config: classpath:logback/logback-dev.xml
